### ISSUE TITLE
undefined type size with anonymous RECORD passed as VAR param

### ISSUE THREAD

**Issue by jtempl** [jtempl/ofront#38]
```
PROCEDURE P ( VAR x : RECORD END );
BEGIN
END P;

```
causes a TRAP when loading the module because the type size of the anonymous record is not defined. While this is not a common programing pattern, it is valid and the fix is simple.
See also https://github.com/Oleg-N-Cher/OfrontPlus/issues/79

**Comment by Oleg-N-Cher** [comment]
Note: the fix also works when anonymous RECORD passed as non-VAR param, i.e:

```
PROCEDURE P ( x : RECORD END );
END P;
```

**Comment by jtempl** [comment]
The fix is not required for the case of passing a value parameter.
Only the case of a VAR param needed the fix.

**Comment by Oleg-N-Cher** [comment]
I had exactly the same error with the size of type -1 on the passing a value parameter too.

With the line `ELSIF mode = Var THEN TypSize(obj^.typ)` the code is:

`__TDESC(Ex__0__desc, 1, 0) = {__TDFLDS("", -1), {-4}};` <-- unknown size (-1)

With the line `ELSIF mode IN {Var, VarPar} THEN TypSize(obj^.typ)` the code is:

`__TDESC(Ex__1__desc, 1, 0) = {__TDFLDS("", 1), {-4}};` <-- known size (one empty element)

Module for testing:

```
MODULE Ex;
PROCEDURE P ( x : RECORD END ); END P;
BEGIN
END Ex.
```

**Comment by jtempl** [comment]
I have tested again with a value param without the fix.
The bug does not show up! This means that it may have been a wrong observation in your test.
Note: a value param is always of mode Var, a VAR param is of mode VarPar.
This means that a value param cannot be affected by the bug fix unless a wrong mode is being used.

**Comment by Oleg-N-Cher** [comment]
You're right, Josef. I misinformed you a little, because I was working with a dialect of Oberon, where this record was passed by reference with the same syntax. So we can consider this problem closed.

Do you have any idea how such a passing of a record could be used? We discussed this issue a bit and decided that such a procedure could not even be called, because its type is not compatible with anything.

**Comment by jtempl** [comment]
I see, you are experimenting with the newest Obern dialect!

I don't know if there is any trick for calling such a procedure and it may
well be
that in the very latest Oberon dialect such a procedure is even forbidden
by the language.

- Josef


Am Mo., 6. Jan. 2020 um 09:05 Uhr schrieb Oleg N. Cher <
notifications@github.com>:

**Comment by Oleg-N-Cher** [comment]
Yes :-) I have supported in Ofront+ a lot of Component Pascal and Oberon-07 features. Also there is supported our experimental dialect with constant arrays, etc - it must be a cross between Oberon-07 and Component Pascal.

I think that a procedure with similar using of the RECORD type definition directly in a parameter can be called with a parameter of type ANYREC (in Component Pascal). Except it, I've only come up with one use of this trick: we can assume a hypothetical case where we need a procedure that can't be called directly, but it must be exported for some purpose. For example, to get its address for low-level purposes. Although this subject raises the question of proper interface design...
