### ISSUE TITLE
[Q] What is the meaning of the RECORD[1], POINTER[1] and ARRAY[1] syntax?

### ISSUE THREAD

**Issue by rochus-keller** [jtempl/ofront#41]
In Modules.Mod, Unix.Mod and WiringPi.Mod there are declarations of the form "RECORD [1]" or "POINTER [1] TO".
In CompilerCmd.Mod, Files.Mod, OfrontOPM.Mod and OfrontOPM.cmdln.Mod there are formal parameter types of "ARRAY [1] OF CHAR". What is the meaning of this syntax? Where can I find the corresponding documentation?

**Comment by jtempl** [comment]
untagged record, pointer to untagged record, uncopied array. It should be described in OfrontUser.Text under "Module SYSTEM".

**Comment by rochus-keller** [comment]
Thanks. Unfortunately my https://github.com/rochus-keller/oberonsystem/ doesn't seem to be compatible with the text file format (looks scrambled). Are there any plain text or PS/PDF or HTML versions of OfrontUser.Text?

**Comment by jtempl** [comment]
Oleg has a pdf of version 1.0 here https://github.com/Oleg-N-Cher/OfrontPlus/blob/master/Docu/Ofront.pdf

**Comment by rochus-keller** [comment]
Great, thanks.
