### ISSUE TITLE
Sym-file isn't updated on POINTER [1] TO ARRAY [1] ...

### ISSUE THREAD

**Issue by Oleg-N-Cher** [jtempl/ofront#7]
To reproduce this error, do the following steps:

	MODULE SDL2; (* Save this file as SDL2.Mod *)
	IMPORT SYSTEM;
	TYPE Pixels* = POINTER [1] TO ARRAY [1] MAX(LONGINT) OF LONGINT;
	END SDL2.

	MODULE SDL2; (* Save this file as SDL2e.Mod *)
	IMPORT SYSTEM;
	TYPE Pixels* = POINTER [1] TO ARRAY [1] OF LONGINT;
	END SDL2.

_zorko@zorko:~/ofront-1.3/bin$ ./ofront -se SDL2.Mod_
SDL2.Mod  translating SDL2  new symbol file    189
_zorko@zorko:~/ofront-1.3/bin$ ./showdef SDL2.sym_
DEFINITION SDL2;

  TYPE
    Pixels = POINTER [1] TO ARRAY [1] 2147483647 OF LONGINT;

END SDL2.

zorko@zorko:~/ofront-1.3/bin$ ./ofront -se SDL2e.Mod_
SDL2e.Mod  translating SDL2    216
_zorko@zorko:~/ofront-1.3/bin$ ./showdef SDL2.sym_
DEFINITION SDL2;

  TYPE
    Pixels = POINTER [1] TO ARRAY [1] 2147483647 OF LONGINT;

END SDL2.

_zorko@zorko:~/ofront-1.3/bin$ rm SDL2.sym_ 
_zorko@zorko:~/ofront-1.3/bin$ ./ofront -se SDL2e.Mod_
SDL2e.Mod  translating SDL2  new symbol file    216
_zorko@zorko:~/ofront-1.3/bin$ ./showdef SDL2.sym_
DEFINITION SDL2;

  TYPE
    Pixels = POINTER [1] TO ARRAY [1] OF LONGINT;

END SDL2.

**Comment by jtempl** [comment]
This is independent from the sysflags.
TYPE A*=POINTER TO ARRAY 1 OF CHAR;
TYPE A*=POINTER TO ARRAY 2 OF CHAR;
Produce the same fingerprints.

**Comment by jtempl** [comment]
There is no real programming error behind the observed behavior. What happens is a collision of fingerprint values computed for type A. As long as A has the same structure but differs only in the number of elements, it gets the same fingerprint and that is why the symbol file change is not detected. The only fix would be to use a different fingerprint function (see OfrontOPM.FPrint) such as ADLER32 or CRC32 but those are certainly slower.

**Comment by jtempl** [comment]
Surprisingly, this example also produces a collision in BlackBox, which uses CRC32. So only a change of the sequence of fingerprint update operations can fix the problem.

**Comment by jtempl** [comment]
Fixed in ofront 1.4.
